# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update pacman package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_facts['distribution'] == "Archlinux"
      become: yes

- hosts: all
  tags: desktop
  roles:
    - desktop
