- name: "KDE | Appearance | Install utils and themes"
  become: yes
  become_user: aur_builder
  tags: kde,appearance
  kewlfft.aur.aur:
    name:
      - klassy-bin
      - kwin-effects-glass-git
      - plasma6-applets-thermal-monitor 
      - plasma6-wallpapers-blurredwallpaper-git 
      - wallpaper-engine-kde-plugin-git 
      - plasma6-applets-eventcalendar 
      - plasma6-applets-arch-update-notifier 
      - 