# Note: `catppuccin_flavor` should be defined in the `roles/desktop` vars (e.g. roles/desktop/vars/main.yml)
# Example value: macchiato-lavender
- name: KDE | Theme | Set Catppuccin color scheme
  tags: KDE,theme,cattpuccin
  community.general.kdeconfig:
    path: "{{ dotconfig_path }}/kdeglobals"
    values:
      - group: General
        key: ColorScheme
        value: "Catppuccin-{{ kde_catppuccin_flavor }}"

- name: KDE | Theme | Install Klassy config
  tags: KDE,theme,klassy
  copy:
    src: "{{ playbook_dir }}/kde/klassyrc"
    dest: "{{ dotconfig_path }}/klassy/klassyrc"
    mode: "0644"

- name: KDE | Theme | Set application style and icon theme to Klassy
  tags: KDE,theme,klassy
  community.general.kdeconfig:
    path: "{{ dotconfig_path }}/kdeglobals"
    values:
      - group: KDE
        key: widgetStyle
        value: "Klassy"
      - group: Icons
        key: Theme
        value: klassy-dark

- name: KDE | Theme | Set window decorations to Klassy
  tags: KDE,theme,klassy
  community.general.kdeconfig:
    path: "{{ dotconfig_path }}/kwinrc"
    values:
      - group: org.kde.kdecoration2
        key: library
        value: org.kde.klassy
      - group: org.kde.kdecoration2
        key: theme
        value: Klassy
