- name: Software | Customization | Install tweaks, KDE scripts
  tags: software,customization,KDE
  kewlfft.aur.aur:
    name:
      - kwin-scripts-krohnkite
      - klassy-bin
      - kwin-effects-glass-git
      - plasma6-applets-thermal-monitor
      - plasma6-wallpapers-blurredwallpaper-git
      - wallpaper-engine-kde-plugin-git
      - plasma6-applets-eventcalendar
      - plasma6-applets-arch-update-notifier
      - plasma6-applets-panel-colorizer

- name: Software | Customization | Install cattpuccin themes
  tags: software,customization,KDE,theme,cattpuccin
  kewlfft.aur.aur:
    name:
      - catppuccin-plasma-colorscheme-macchiato
      - catppuccin-plasma-colorscheme-mocha
