default-remote: matrix
remotes:
  images:
    protocol: simplestreams
    public: true
    addr: https://images.linuxcontainers.org
  local:
    protocol: incus
    public: false
    addr: unix://
  matrix:
    last_working_address: https://192.168.1.2:8443
    auth_type: oidc
    project: k3s
    protocol: incus
    public: false
    addr: https://192.168.1.2:8443
  matrix-tls:
    last_working_address: https://192.168.1.2:8443
    auth_type: tls
    protocol: incus
    public: false
    addr: https://192.168.1.2:8443
aliases: {}
defaults:
  list_format: ""
  console_type: ""
  console_spice_command: ""
  no_color: false
