# Browsers: install zen + chromium, and remove the preinstalled Firefox.

- name: Browsers | Install browsers
  tags: software,browsers,zen,chromium
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
        - zen-browser-bin
        - chromium

# We already have zen and chromium so who cares
- name: Browsers | Uninstall firefox
  tags: software,browsers
  become: yes # Removing packages requires actual root rather than aur_builder
  become_user: root
  pacman:
    remove_nosave: true
    state: removed
    name:
        - firefox

- name: Browsers | Cleanup firefox data
  tags: software,browsers
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ dotconfig_path }}/mozilla/firefox"
    - "{{ dotcache_path }}/mozilla/firefox"
